#!/bin/bash

./system_backup.sh

root_dev=`grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{printf $NF}'`
if test "$root_dev" = "/dev/mmcblk0p7";then
cp -rf ./boot/config-noobs-nomal.txt ./boot/config.txt.bak
else
cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
fi
echo "dtparam=i2c_arm=on" >> ./boot/config.txt.bak
echo "dtparam=spi=on" >> ./boot/config.txt.bak
echo "enable_uart=1" >> ./boot/config.txt.bak
echo "display_rotate=0" >> ./boot/config.txt.bak
echo "max_usb_current=1" >> ./boot/config.txt.bak
echo "config_hdmi_boost=7" >> ./boot/config.txt.bak
echo "hdmi_group=2" >> ./boot/config.txt.bak
echo "hdmi_mode=87" >> ./boot/config.txt.bak
echo "hdmi_drive=1" >> ./boot/config.txt.bak
echo "hdmi_cvt 1024 600 60 6 0 0 0" >> ./boot/config.txt.bak
cp -rf ./boot/config.txt.bak /boot/config.txt
#cp -rf ./boot/config-7C-1024x600.txt /boot/config.txt
#if test "$root_dev" = "/dev/mmcblk0p7";then
#cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
#else
#cp ./usr/cmdline.txt /boot/
#fi
cp ./usr/inittab /etc/
cp -rf ./usr/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbturbo.conf

if [ ! -d /etc/X11/xorg.conf.d ]; then
mkdir /etc/X11/xorg.conf.d
fi
cp ./usr/40-libinput.conf-0 /etc/X11/xorg.conf.d/40-libinput.conf
touch ./.have_installed
echo "hdmi:capacity:7C-1024x600:0:1024:600" > ./.have_installed
sync
sync
sleep 1
if [ $# -eq 1 ]; then
./rotate.sh $1
elif [ $# -gt 1 ]; then
echo "Too many parameters"
fi

echo "reboot now"
reboot
